const languageCodes = {
    "es-ES": "Spanish",
    "en-US": "English-US",
    "en-GB": "English-GB",
    "fr-FR": "French-FR",
    "fr-CA": "French-CA",
    "de-DE": "German",
    "pt-PT": "Portuguese-PT",
    "pt-BR": "Portuguese-BR",
    "it-IT": "Italian",
    "ja-JP": "Japanese",
    "zh-CN": "Chinese",
    "zh-TW": "Chinese",
    "ru-RU": "Russian",
    "ko-KR": "Korean",
    "ar-SA": "Arabic",
    "hi-IN": "Hindi",
    "bn-BD": "Bengali",
    "pa-IN": "Punjabi",
    "te-IN": "Telugu",
    "tr-TR": "Turkish",
    "af-ZA": "Afrikaans",
    "sq-AL": "Albanian",
    "am-ET": "Amharic",
    "hy-AM": "Armenian",
    "az-AZ": "Azerbaijani",
    "eu-ES": "Basque",
    "be-BY": "Belarusian",
    "bs-BA": "Bosnian",
    "bg-BG": "Bulgarian",
    "ca-ES": "Catalan",
    "zh-HK": "Chinese (Hong Kong)",
    "hr-HR": "Croatian",
    "cs-CZ": "Czech",
    "da-DK": "Danish",
    "nl-NL": "Dutch",
    "en-AU": "English (Australia)",
    "en-CA": "English (Canada)",
    "en-IN": "English (India)",
    "en-IE": "English (Ireland)",
    "en-NZ": "English (New Zealand)",
    "en-ZA": "English (South Africa)",
    "et-EE": "Estonian",
    "fil-PH": "Filipino",
    "fi-FI": "Finnish",
    "fr-BE": "French (Belgium)",
    "gl-ES": "Galician",
    "ka-GE": "Georgian",
    "el-GR": "Greek",
    "gu-IN": "Gujarati",
    "ht-HT": "Haitian Creole",
    "ha-Latn-NG": "Hausa (Latin)",
    "iw-IL": "Hebrew",
    "hi-Latn": "Hindi (Latin)",
    "hu-HU": "Hungarian",
    "is-IS": "Icelandic",
    "ig-NG": "Igbo",
    "id-ID": "Indonesian",
    "ga-IE": "Irish",
    "it-CH": "Italian (Switzerland)",
    "jv-ID": "Javanese",
    "kn-IN": "Kannada",
    "kk-KZ": "Kazakh",
    "km-KH": "Khmer",
    "rw-RW": "Kinyarwanda",
    "kok-IN": "Konkani",
    "ku-Arab-IQ": "Kurdish (Arabic, Iraq)",
    "ky-KG": "Kyrgyz",
    "lo-LA": "Lao",
    "lv-LV": "Latvian",
    "lt-LT": "Lithuanian",
    "nds-DE": "Low German",
    "lb-LU": "Luxembourgish",
    "mk-MK": "Macedonian",
    "ms-BN": "Malay (Brunei)",
    "ms-MY": "Malay (Malaysia)",
    "ml-IN": "Malayalam",
    "mt-MT": "Maltese",
    "mi-NZ": "Maori (New Zealand)",
    "mr-IN": "Marathi",
    "moh-CA": "Mohawk",
    "mn-MN": "Mongolian (Cyrillic)",
    "ne-NP": "Nepali",
    "se-NO": "Northern Sami",
    "nb-NO": "Norwegian Bokmål",
    "nn-NO": "Norwegian Nynorsk",
    "or-IN": "Odia",
    "ps-AF": "Pashto",
    "fa-IR": "Persian",
    "pl-PL": "Polish",
    "pt-AO": "Portuguese (Angola)",
    "pa-Arab-PK": "Punjabi (Arabic, Pakistan)",
    "quz-PE": "Quechua",
    "ro-RO": "Romanian",
    "rm-CH": "Romansh",
    "nyn-UG": "Runyankore",
    "ru-KG": "Russian (Kyrgyzstan)",
    "smn-FI": "Sami (Inari)",
    "smj-NO": "Sami (Lule)",
    "se-FI": "Sami (Northern)",
    "sms-FI": "Sami (Skolt)",
    "sma-NO": "Sami (Southern)",
    "sa-IN": "Sanskrit",
    "sr-Cyrl-BA": "Serbian (Cyrillic, Bosnia and Herzegovina)",
    "sr-Cyrl-RS": "Serbian (Cyrillic, Serbia)",
    "sr-Latn-BA": "Serbian (Latin, Bosnia and Herzegovina)",
    "sr-Latn-RS": "Serbian (Latin, Serbia)",
    "nso-ZA": "Sesotho sa Leboa",
    "tn-ZA": "Setswana",
    "si-LK": "Sinhala",
    "sk-SK": "Slovak",
    "sl-SI": "Slovenian",
    "xog-UG": "Soga",
    "so-SO": "Somali",
    "es-AR": "Spanish (Argentina)",
    "es-BO": "Spanish (Bolivia)",
    "es-CL": "Spanish (Chile)",
    "es-CO": "Spanish (Colombia)",
    "es-CR": "Spanish (Costa Rica)",
    "es-DO": "Spanish (Dominican Republic)",
    "es-EC": "Spanish (Ecuador)",
    "es-SV": "Spanish (El Salvador)",
    "es-GT": "Spanish (Guatemala)",
    "es-HN": "Spanish (Honduras)",
    "es-MX": "Spanish (Mexico)",
    "es-NI": "Spanish (Nicaragua)",
    "es-PA": "Spanish (Panama)",
    "es-PY": "Spanish (Paraguay)",
    "es-PE": "Spanish (Peru)",
    "es-PR": "Spanish (Puerto Rico)",
    "es-UY": "Spanish (Uruguay)",
    "es-VE": "Spanish (Venezuela)",
    "sw-KE": "Swahili",
    "sv-SE": "Swedish",
    "gsw-CH": "Swiss German",
    "syr-SY": "Syriac",
    "tg-Cyrl-TJ": "Tajik (Cyrillic, Tajikistan)",
    "tzm-Latn-DZ": "Tamazight (Latin, Algeria)",
    "ta-IN": "Tamil",
    "tt-RU": "Tatar",
    "th-TH": "Thai",
    "bo-CN": "Tibetan",
    "tr-IN": "Turkish (Turkey)",
    "tk-TM": "Turkmen",
    "ug-CN": "Uighur",
    "uk-UA": "Ukrainian",
    "hsb-DE": "Upper Sorbian",
    "ur-PK": "Urdu",
    "uz-Cyrl-UZ": "Uzbek (Cyrillic, Uzbekistan)",
    "uz-Latn-UZ": "Uzbek (Latin, Uzbekistan)",
    "vi-VN": "Vietnamese",
    "cy-GB": "Welsh",
    "wo-SN": "Wolof",
    "sah-RU": "Yakut",
    "ii-CN": "Yi",
    "yo-NG": "Yoruba",
    "dje-NE": "Zarma",
    "zu-ZA": "Zulu"
};

export default languageCodes;
